### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by quancs** [LiuChangFreeman/OneIndex-Serverless#7]
不清楚为什么会报这个错误，当前步骤是访问github page页，返回的是500错误，我在阿里云控制台测试的时候（list）函数，返回的错误如下：

Traceback (most recent call last):

  File "/code/flask/app.py", line 2292, in wsgi_app

    response = self.full_dispatch_request()

  File "/code/flask/app.py", line 1815, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/code/flask/app.py", line 1718, in handle_user_exception

    reraise(exc_type, exc_value, tb)

  File "/code/flask/app.py", line 1813, in full_dispatch_request

    rv = self.dispatch_request()

  File "/code/flask/app.py", line 1799, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/code/main.py", line 172, in list

    response={"error":e.message,"data":data}

UnboundLocalError: local variable 'data' referenced before assignment

FC Invoke End RequestId: 2c5e8340-0f00-4592-8df0-5ca42a11f62e

Duration: 2.76 ms, Billed Duration: 100 ms, Memory Size: 3072 MB, Max Memory Used: 58.32 MB

**Comment by quancs** [comment]
修改代码为：
response={"error":e.message,"data":"UNKNOWN"}
之后，返回的数据为：
{"data": "UNKNOWN", "error": "'NoneType' object has no attribute '__getitem__'"}

**Comment by quancs** [comment]
我网址打开错了，不好意思
